(PDB-2791) Add tests (detritus, exceptions, etc.) [RFC]
puppetlabs/stockpile pull request #12
Opened 2016-09-16 21:20 UTC by rbrw

2016-09-16 21:21 UTC, rbrw commented
RFC: regarding the new "orphan" exception

2016-09-16 21:21 UTC, rbrw commented
This is based on #11 and shouldn't be merged yet.

2016-09-21 14:31 UTC, senior commented on src/puppetlabs/stockpile/queue.clj
> +(defn- write-stream [stream dest]
This needs type hints for stream and dest

2016-09-21 14:34 UTC, senior commented on src/puppetlabs/stockpile/queue.clj
> +             (ex-info (str "unable to delete temp file " tmp " after error")
We talked about this Monday and I know you're working up some changes here, I'll hold off on the rest of this review until that's done.

2016-09-21 14:34 UTC, senior requested changes
You've already got some changes coming, I'll look at it again once the related PR goes in.

2016-09-30 19:39 UTC, senior commented on src/puppetlabs/stockpile/queue.clj
> +  durably-establish."
This public function is referencing the docs in a private function, that seems wrong to me as usually private functions don't have their docs published. Is there a list of all of the different exceptions that need to be caught by callers of this function?

2016-09-30 21:28 UTC, rbrw commented on src/puppetlabs/stockpile/queue.clj
> +  durably-establish."
Good point; I've included the docs in the create and store docstrings and elaborated on how we think callers might want to handle invocations.

2016-09-30 21:41 UTC, merged